### ISSUE TITLE
Compilation flag to build without singletons

### ISSUE THREAD

**Issue by int-index** [clash-lang/ghc-typelits-knownnat#15]
I use this library to prove `KnownNat (n + 1)` from `KnownNat n`, installing `singletons` is a bit of an overkill.

**Comment by christiaanb** [comment]
It’s never really bothered me personally I guess, because a lot of my code depends on `singletons`, so I used some of its types without too much thought.

Removing the dependency shouldn’t be too much work I think.

**Comment by christiaanb** [comment]
I've removed the `singletons`  dependency and will probably do a release between Christmas and New Years.

**Comment by int-index** [comment]
Thanks!
