### ISSUE TITLE
Limited forms of subtraction

### ISSUE THREAD

**Issue by ggreif** [clash-lang/ghc-typelits-knownnat#2]
`3 * a - a` == `2 * a`

I *think* I have an actual use-case for this at work. Will try to post an example.

**Comment by christiaanb** [comment]
Can this issue be closed?

**Comment by ggreif** [comment]
I saw a testcase like this in your tests, so *I think* you can close this.

**Comment by ggreif** [comment]
Pull request #5 seems to fail. Let's wait a bit before closing. But possibly the test is badly put.

**Comment by christiaanb** [comment]
This works now
